I-Form/I-Form/Models/FormViewModel.cs
using I_Form.Data.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace I_Form.Models
{
    public class FormViewModel
    {
        public Guid Id { get; set; }

        public string Title { get; set; }

        public string Description { get; set; }

        public string AuthorName { get; set; }

        public Guid AuthorId { get; set; }

        public ICollection<TextQuestionViewModel> TextQuestions { get; set; }

        public FormViewModel()
        {
            TextQuestions = new List<TextQuestionViewModel>();
        }
    }
}

I-Form/I-Form/Controllers/DocumentQuestionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using I_Form.Models;
using I_Form.Services.Contracts;
using I_Form.Services.DTOEntities;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace I_Form.Controllers
{
    public class DocumentQuestionController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IDocumentQuestionService _documentQuestionService;

        public DocumentQuestionController(IMapper mapper, IDocumentQuestionService documentQuestionService)
        {
            this._mapper = mapper ?? throw new ArgumentNullException(nameof(mapper)); ;
            this._documentQuestionService = documentQuestionService ?? throw new ArgumentNullException(nameof(documentQuestionService));
        }
        // GET: OptionQuestions
        public async Task<IActionResult> Index(Guid formId)
        {
            var questionsDTO = await _documentQuestionService.GetAllAsync(formId);
            var questionsVM = _mapper.Map<ICollection<DocumentQuestionViewModel>>(questionsDTO);
            return View(questionsVM);
        }

        // GET: OptionQuestions/Details/5
        public async Task<IActionResult> Details(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var question = await _documentQuestionService.GetAsync(id);

            var questionVM = _mapper.Map<DocumentQuestionViewModel>(question);

            if (questionVM == null)
            {
                return NotFound();
            }

            return View(questionVM);
        }

        [HttpGet]
        public ActionResult Create()
        {
            var documentQuestion = new DocumentQuestionViewModel();
            return PartialView("_DocumentQuestionPartial", documentQuestion);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateDocumentQuestion(DocumentQuestionViewModel question)
        {
            var documentQuestionDTO = _mapper.Map<DocumentQuestionDTO>(question);
            await _documentQuestionService.CreateAsync(documentQuestionDTO);

            return PartialView("_DocumentQuestionPartial", question);
        }



        // POST: OptionQuestions/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditOptionQuestion(DocumentQuestionViewModel question)
        {

            if (ModelState.IsValid)
            {
                var questionDTO = _mapper.Map<DocumentQuestionDTO>(question);
                await _documentQuestionService.EditAsync(questionDTO);
                return RedirectToAction(nameof(Index));
            }

            return View(question);
        }

        // GET: OptionQuestions/Delete/5
        public ActionResult Delete(Guid id)
        {
            return View();
        }
    }
}

I-Form/I-Form/Controllers/OptionQuestionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using I_Form.Data.Entities;
using I_Form.Models;
using I_Form.Services.Contracts;
using I_Form.Services.DTOEntities;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace I_Form.Controllers
{
    public class OptionQuestionsController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IOptionsQuestionService _optionsQuestionService;

        public OptionQuestionsController(IMapper mapper,IOptionsQuestionService optionsQuestionService)
        {
            this._mapper = mapper ?? throw new ArgumentNullException(nameof(mapper)); ;
            this._optionsQuestionService = optionsQuestionService ?? throw new ArgumentNullException(nameof(optionsQuestionService));
        }
        // GET: OptionQuestions
        public async Task<IActionResult> Index(Guid formId)
        {
            var questionsDTO = await _optionsQuestionService.GetAllAsync(formId);
            var questionsVM = _mapper.Map<ICollection<OptionsQuestionViewModel>>(questionsDTO);
            return View(questionsVM);
        }

        // GET: OptionQuestions/Details/5
        public async Task<IActionResult> Details(Guid id)
        {
          if (id == null)
            {
                return NotFound();
            }

            var question = await _optionsQuestionService.GetOptionsQuestion(id);

            var questionVM = _mapper.Map<OptionsQuestionViewModel>(question);

            if (questionVM == null)
            {
                return NotFound();
            }

            return View(questionVM);
        }

        // GET: OptionQuestions/Create
        [HttpGet]
        public ActionResult Create()
        {
            var optionQuestion = new OptionsQuestionViewModel();
            return PartialView("_OptionsQuestionPartial", optionQuestion);
        }

        // POST: OptionQuestions/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateOptionQuestion(OptionsQuestionViewModel question)
        {
                var optionQuestionDTO = _mapper.Map<OptionsQuestionDTO>(question);
                await _optionsQuestionService.CreateAsync(optionQuestionDTO);

            return PartialView("_OptionsQuestionPartial", question);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateOption(OptionViewModel option)
        {
            var optionDTO = _mapper.Map<OptionDTO>(option);
            await _optionsQuestionService.CreateOptionAsync(optionDTO);

            return View();                      
        }
    
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditOption(Guid Id,OptionViewModel option)
        {
            if (Id != option.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var optionDTO = _mapper.Map<OptionDTO>(option);
                await _optionsQuestionService.EditOptionAsync(Id, optionDTO);
                return RedirectToAction(nameof(Index));
            }

            return View(option);
        }

        // POST: OptionQuestions/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditOptionQuestion(Guid Id,OptionsQuestionViewModel question)
        {
            if (Id != question.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var questionDTO = _mapper.Map<OptionsQuestionDTO>(question);
                await _optionsQuestionService.EditAsync(Id, questionDTO);
                return RedirectToAction(nameof(Index));
            }

            return View(question);
        }

        // GET: OptionQuestions/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

          }
}

I-Form/I-Form/Controllers/ResponsesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using I_Form.Data;
using I_Form.Data.Entities;
using I_Form.Models;
using AutoMapper;
using I_Form.Services.Contracts;
using System.Security.Policy;
using Azure;

namespace I_Form.Controllers
{
    public class ResponsesController : Controller
    {
        private readonly FormContext _context;
        private readonly IMapper mapper;
        private readonly IResponsesService responsesService;
        private readonly ITextQuestionService textQuestionService;

        public ResponsesController(FormContext context,IMapper mapper,IResponsesService responsesService,ITextQuestionService textQuestionService)
        {
            _context = context;
            this.mapper = mapper;
            this.responsesService = responsesService;
            this.textQuestionService = textQuestionService;
        }

        // GET: Responses
        public async Task<IActionResult> Index()
        {
            var formContext = _context.Responses.Include(r => r.Form);
            return View(await formContext.ToListAsync());
        }

        [HttpGet]
        public async Task<IActionResult> Submit(Guid id)
        {
            var responseDTO = await this.responsesService.GetAsync(id);
            var textQDTO = await this.textQuestionService.GetAllTextQuestionAsync(id);
            var textQVM = mapper.Map<List<TextQuestionViewModel>>(textQDTO);
            var responseVM = mapper.Map<ResponsesViewModel>(responseDTO);
            responseVM.TextQuestionsVM = textQVM;
                       return View(responseVM);
        }

        [HttpPost]
        public async Task<IActionResult> Submit(ResponsesViewModel responseVM)
        {
            var response = new Responses();
            response.FormId = responseVM.FormId;
            response.CreatedOn = DateTime.Now;
            response.TextQuestionAnswers = responseVM.TextQuestionsVM.Select(tq => new TextQuestionAnswers()
            {
                Answer = tq.Content
            }).ToList();

            await this._context.Responses.AddAsync(response);
            await this._context.SaveChangesAsync();

            TempData["SuccessMessage"] = "The response has been submitted successfully!";

            return RedirectToAction(nameof(Submit));
        }

        // GET: Responses/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var responses = await _context.Responses
                .Include(r => r.Form)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (responses == null)
            {
                return NotFound();
            }

            return View(responses);
        }

        // GET: Responses/Create
        public IActionResult Create()
        {
            ViewData["FormId"] = new SelectList(_context.Forms, "Id", "Description");
            return View();
        }

        // POST: Responses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FormId,CreatedOn")] Responses responses)
        {
            if (ModelState.IsValid)
            {
                responses.Id = Guid.NewGuid();
                _context.Add(responses);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["FormId"] = new SelectList(_context.Forms, "Id", "Description", responses.FormId);
            return View(responses);
        }

        // GET: Responses/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var responses = await _context.Responses.FindAsync(id);
            if (responses == null)
            {
                return NotFound();
            }
            ViewData["FormId"] = new SelectList(_context.Forms, "Id", "Description", responses.FormId);
            return View(responses);
        }

        // POST: Responses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,FormId,CreatedOn")] Responses responses)
        {
            if (id != responses.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(responses);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ResponsesExists(responses.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["FormId"] = new SelectList(_context.Forms, "Id", "Description", responses.FormId);
            return View(responses);
        }

        // GET: Responses/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var responses = await _context.Responses
                .Include(r => r.Form)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (responses == null)
            {
                return NotFound();
            }

            return View(responses);
        }

        // POST: Responses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var responses = await _context.Responses.FindAsync(id);
            _context.Responses.Remove(responses);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ResponsesExists(Guid id)
        {
            return _context.Responses.Any(e => e.Id == id);
        }
    }
}

I-Form/I-Form/Views/Forms/Create.cshtml
@model FormViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/css/formCreate.css" rel="stylesheet" />


<div class="content">
    <form asp-action="Create" id="formId">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Title" class="control-label"></label>
            <input asp-for="Title" class="form-control" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Description" class="control-label"></label>
            <input asp-for="Description" class="form-control" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>

        <div class="container">
            <button type="submit" style="background-color:#1fe8b6" class="bttn">Create</button>
        </div>
    </form>
</div>


@*<div>
        <a asp-action="Index">Back to List</a>
    </div>*@

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

<script type="text/javascript">
    var createBttn = $('#createBttn');

    //.live to stay on the page after is clicked?
    createBttn.on('click', function () {

    let formData = $('#formId').serialize();

        $.ajax({
            method: "POST",
            url: "/Forms/Create",
            data: formData,
            success: function (result) {
                alert('Yay! It worked');

            },

            error: function (result) {

                console.log(formData);


                alert('Oh no :(');
            }
        });

    });
</script>

}

I-Form/I-Form/Views/Forms/Delete.cshtml
@model FormViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Form</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

I-Form/I-Form/Views/Forms/Details.cshtml
@model FormViewModel

@{
    ViewData["Title"] = "Details";
}

    <link href="~/css/formDetails.css" rel="stylesheet" />

    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <div id="formContainer">
<div id="PlaceHolderHere"></div>
<div id="PlaceHolderHere2"></div>



<div class="container">
    <h1>
        @Html.DisplayFor(model => model.Title)
    </h1>
    <hr />
    <h2>
        @Html.DisplayFor(model => model.Description)
    </h2>

</div>

@if (Model.TextQuestions.Any())
{
    @foreach (var item in Model.TextQuestions)
    {
        <div class="textQ_containter"data-questionId="@Model.Id">
        <div>
            <h2 class="text-center">
                @item.Title
            </h2>

            <p class="desc">
                @item.Description
            </p>


            @if (item.IsLongAnswer == true)
            {
                <p class="impact text-center" >
                    Is Long Answer
                </p>
            }
            @if (item.IsRequired == true)
            {
                <p class="impact text-center">
                    Is Required
                </p>
            }
        </div>
        <div class="text-center">

        <button type="button" data-questionId="@Model.Id" class="btn btn-primary editQuestionBtn">Edit</button>
        </div>

        </div>
    }
}

<div class="container">
<div id="txtQC" class=""></div>
</div>

<div class="modal fade" id="mainModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id="saveBtn">Save</button>
      </div>
    </div>
  </div>
</div>

<button type="button" id="createTQBtn" class="btn btn-primary" data-toggle="modal" data-target="#mainModal"
        data-formid="@Model.Id" data-url="@Url.Action("CreateTextQuestion")">
    Create TextQuestion
</button>
<button type="button" id="idButton2" class="btn btn-primary" data-toggle="ajax-modal" data-target="#OptionQeustionVM"
        data-formid="@Model.Id" data-url="@Url.Action("CreateOptionQuestion")">
    Create Option Question
</button>
<button type="button" id="idButton3" class="btn btn-primary" data-toggle="ajax-modal" data-target="#DocumentQuestionVM"
        data-formid="@Model.Id" data-url="@Url.Action("CreateDocumentQuestion")">
    Create Document Question
</button>




@section Scripts {
        <script>
            //Add text question
          //Add text question
          $('#createTQBtn').on('click', function () {
            $.ajax({
              method: 'GET',
              url: '/TextQuestions/CreateTextQuestion'
            }).done(function (createQuestionPartialView) {
              $('div.modal-body').html(createQuestionPartialView)
              $('#mainModal').modal('show')
            })
          debugger


            $('#saveBtn').on('click', function () {
              let formData = $('#textQuestionId').serialize()
              let formId = $('createTQBtn').attr('data-formid')

              $.ajax({
                method: 'POST',
                url: `/TextQuestions/CreateTextQuestion?FormId=${formId}`,
                data: formData
              }).done(function (data) {
                $('#mainModal').modal('hide')

                //let cardElement = $($eventTarget.closest('.textQ_container'))
                $('#txtQC').append(data).collapse('show')
              })
            })
          })
           
          

          //Edit text question
          function editBtnHandler(event) {
            $eventTarget = $(event.target)

            if ($eventTarget.hasClass('editQuestionBtn')) {
              let questionId = $eventTarget.attr('data-questionId')

              $.ajax({
                method: 'GET',
                url: `/TextQuestion/Edit/`,
                data: questionId
              }).done(function (createTextQuestionPartialView) {
                $('div.modal-body').html(createTextQuestionPartialView)
                $('#mainModal').modal('show')
              })

              $('#saveBtn').off()

              $('#saveBtn').on('click', function () {
                let formData = $('#editQuestionForm').serialize()

                $.ajax({
                  method: 'POST',
                  url: `/TextQuestion/Edit`,
                  data: formData
                }).done(function (saveEdit) {
                  $('#mainModal').modal('hide')
                  let cardElement = $($eventTarget.closest('.textQ_container'))
                  cardElement.innerHtml = saveEdit
                })
              })



            }
          }
         
          $('#formContainer').on('click',editBtnHandler)

        </script>

    }
}
    </div>

I-Form/I-Form/Views/Forms/Edit.cshtml
@model FormViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Form</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

I-Form/I-Form/Views/Forms/Index.cshtml
@model IEnumerable<FormViewModel>

@{
    ViewData["Title"] = "Index";
}

<link href="~/css/formIndex.css" rel="stylesheet" />

@foreach (var item in Model)
{
    <div class="contentWrap">

    <div class="formContainer">
        <div class="formContainer_img">
            <img src="~/css/images/natureBG.jpeg" />
        </div>
        <div class="formContainer_info">
            <h1 class="formContainer_title">
                @item.Title
            </h1>
            <p class="formContainer_desc">@item.Description</p>

            <a class="formContainer_button" asp-action="Details" asp-route-id="@item.Id">Details</a>
            <a class="formContainer_button" asp-controller="Responses" asp-action="Submit" asp-route-id="@item.Id">Fill form</a>
        </div>
    </div>
    </div>



    @*<a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>

        <a asp-action="Details" asp-route-id="@item.Id">Details</a>*@


}

@if (User.Identity.IsAuthenticated)
{
    <p>
        <br />
        <a class="btn btn-primary" role="button" asp-action="Create">Create New</a>
    </p>
}

I-Form/I-Form/Views/Forms/_DocumentQuestionPartial.cshtml
@model DocumentQuestionViewModel

<div class="modal fade" id="addDocumentQuestionViewModel">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="DocumentQuestionVM">Add DocumentQuestion</h4>
        <button type="button" class="close" data-dismiss="modal">
          <span>X</span>
        </button>
      </div>
      <div class="modal-body">
        <form asp-controller="DocumentQuestion" asp-action="CreateDocumentQuestion">
          <div class="form-group">
            <label asp-for="Title"></label>
            <input id="modalTitle" asp-for="Title" class="form-control" />
            <span asp-validation-for="Title" class="text-danger"></span>
          </div>
          <div class="form-group">
            <label asp-for="Description"></label>
            <input id="modalDesc" asp-for="Description" class="form-control" />
            <span asp-validation-for="Description" class="text-danger"></span>
          </div>

        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" data-save="modal">Save</button>
      </div>
    </div>
  </div>
</div>

I-Form/I-Form/Views/Forms/_OptionsQuestionPartial.cshtml
@model OptionsQuestionViewModel

 <form asp-controller="OptionQuestions" asp-action="CreateOptionQuestion">
                    <div class="form-group">
                        <label asp-for="Title"></label>
                        <input asp-for="Title" class="form-control" />
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description"></label>
                        <input asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <button type="button" id="saveOptionsQuestionBtn" asp-controller="OptionsQuestions" asp-action="CreateOption">Create Option</button>
                </form>