I-Form/I-Form/Models/TextQuestionViewModel.cs
using System;

namespace I_Form.Models
{
    public class TextQuestionViewModel
    {
        public Guid Id{ get; set; }

        public string Title { get; set; }

        public string  Description { get; set; }

        public Guid FormId { get; set; }

        public bool IsRequired { get; set; }
        public bool IsLongAnswer { get; set; }
        public string Content { get; set; }

    }
}

I-Form/I-Form/Controllers/TextQuestionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using I_Form.Data.Entities;
using I_Form.Models;
using I_Form.Services.Contracts;
using I_Form.Services.DTOs;
using Microsoft.AspNetCore.Mvc;

namespace I_Form.Controllers
{
    public class TextQuestionsController : Controller
    {
        private readonly IMapper _mapper;

        private readonly ITextQuestionService _txtQService;

        private readonly IFormService _formService;

        public TextQuestionsController(IMapper mapper, ITextQuestionService txtQService, IFormService formService)
        {
            _mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
            _txtQService = txtQService ?? throw new ArgumentNullException(nameof(txtQService));
            _formService = formService ?? throw new ArgumentNullException(nameof(formService));
        }

        [HttpGet]
        //Get : TextQuestions
        public async Task<IActionResult> Index()
        {
            var txtQs = await _txtQService.GetAllTextQuestionAsync();

            var txtQViewModels = _mapper.Map<List<TextQuestionViewModel>>(txtQs);

            return View(txtQViewModels);
        }

        [HttpGet]
        //Get : TextQuestions/Details/1
        public async Task<IActionResult> Details(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var txtQ = await _txtQService.GetTextQuestionAsync(id);

            var txtQViewModel = _mapper.Map<FormViewModel>(txtQ);

            if (txtQ == null)
            {
                return NotFound();
            }

            return View(txtQViewModel);
        }

        [HttpGet]
        public IActionResult CreateTextQuestion()
        {
            var textQ = new TextQuestionViewModel();
            return PartialView("_TextQuestionPartial",textQ);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateTextQuestion(TextQuestionViewModel textQuestionViewModel)
        {

            var txtQDTO = _mapper.Map<TextQuestionDTO>(textQuestionViewModel);

            await _txtQService.CreateTextQuestionAsync(txtQDTO);

            var txtQVM = _mapper.Map<TextQuestionViewModel>(txtQDTO);

            

            return View("Details");
        }
        [HttpGet]
        public async Task<IActionResult> Edit(Guid Id)
        {
            var question = await this._txtQService.GetTextQuestionAsync(Id);
            return PartialView("_TextQuestionPartial", question);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Edit(Guid Id, TextQuestionViewModel txtQViewModel)
        {
            if (Id != txtQViewModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _txtQService.UpdateTextQuestionAsync(Id, txtQViewModel.Title, txtQViewModel.Description);
                return RedirectToAction(nameof(Index));
            }

            return View(txtQViewModel);
        }
    }
}

I-Form/I-Form/Views/TextQuestions/Create.cshtml
@model I_Form.Models.TextQuestionViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>TextQuestionViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

I-Form/I-Form/Views/TextQuestions/Details.cshtml
@model I_Form.Models.TextQuestionViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>
<div>
    <h4>TextQuestionViewModel</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

I-Form/I-Form/Views/TextQuestions/Edit.cshtml
@model I_Form.Models.TextQuestionViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>TextQuestionViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

I-Form/I-Form/Views/TextQuestions/Index.cshtml
@model IEnumerable<I_Form.Models.TextQuestionViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

I-Form/I-Form/Views/TextQuestions/_TextQuestionPartial.cshtml
@model TextQuestionViewModel

                <form id="textQuestionId"asp-controller="TextQuestions" asp-action="CreateTextQuestion">
                    <div class="form-group">
                      <input type="hidden" value="@Model.Id" name="TextQuestionViewModel.Id"/>
                      <input type="hidden" value="@Model.FormId" name="FormViewModel.Id"/>
                        <label asp-for="Title"></label>
                        <input id="modalTitle" asp-for="Title" class="form-control" />
                        <span asp-validation-for="Title" class="text-danger"></span>
                        <label asp-for="Description"></label>
                        <input id="modalDesc" asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span> 
                    </div>
                    <input id="modalCheckLongA" type="checkbox"/> Long answer
                    <input id="modalCheckReqA" type="checkbox"/> Required answer
                   
                </form>
           