I-Form/I-Form/Controllers/FormsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using I_Form.Data;
using I_Form.Data.Entities;
using I_Form.Services.Contracts;
using AutoMapper;
using I_Form.Models;
using I_Form.Services.DTOEntities;
using System.Security.Cryptography;
using Microsoft.AspNetCore.Authorization;
using I_Form.Services.DTOs;
using System.Security.Claims;

namespace I_Form.Controllers
{
    [AutoValidateAntiforgeryToken]
    public class FormsController : Controller
    {
        private readonly FormContext _context;

            private readonly IMapper _mapper;

            private readonly IFormService _formService;
            private readonly ITextQuestionService _txtQService;

        public FormsController(IFormService formService, IMapper mapper, ITextQuestionService txtQService)
        {
            _formService = formService;
            _mapper = mapper;
            _txtQService = txtQService;
        }

        // GET: Forms
        public async Task<IActionResult> Index()
        {
            var formDTO = await _formService.GetAllFormsAsync();

            var formViewModel = _mapper.Map<List<FormViewModel>>(formDTO);

            return View(formViewModel);
        }

        // GET: Forms/Details/5
        public async Task<IActionResult> Details(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var form = await _formService.GetFormAsync(id);

            var formViewModel = _mapper.Map<FormViewModel>(form);

            if (form == null)
            {
                return NotFound();
            }

            return View(formViewModel);
        }

        // GET: Forms/Create
        public IActionResult Create()
        {
            var form = new FormViewModel();
            
            return View(form);
        }

        [HttpGet]
        public IActionResult CreateTextQuestion()
        {
            var txtQ = new TextQuestionViewModel();
            return PartialView("_TextQuestionPartial", txtQ);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(FormViewModel form)
        {
            if (ModelState.IsValid)
            {

                var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);

                var id = new Guid(userId);

                form.AuthorId = id;

                var formDTO = _mapper.Map<FormDTO>(form);
                await _formService.CreateFormAsync(formDTO);
                var formVM = _mapper.Map<FormViewModel>(formDTO);

                return View("Details",formVM);
            }
           
            return View(form);
        }

   



        // GET: Forms/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var form = await _context.Forms.FindAsync(id);
            if (form == null)
            {
                return NotFound();
            }
            ViewData["AuthorId"] = new SelectList(_context.Users, "Id", "Id", form.AuthorId);
            return View(form);
        }

        // POST: Forms/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [IgnoreAntiforgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Title,Description,DeletedOn,IsDeleted,CreatedOn,UpdatedOn,AuthorId")] Form form)
        {
            if (id != form.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(form);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FormExists(form.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorId"] = new SelectList(_context.Users, "Id", "Id", form.AuthorId);
            return View(form);
        }

        // GET: Forms/Delete/5
        public async Task<IActionResult> Delete(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var form = await _formService.GetFormAsync(id);

            if (form == null)
            {
                return NotFound();
            }

            var formVM = _mapper.Map<FormViewModel>(form);

            return View(formVM);
        }

        // POST: Forms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var form = await _formService.DeleteFormAsync(id);
            return RedirectToAction(nameof(Index));
        }

        private bool FormExists(Guid id)
        {
            return _context.Forms.Any(e => e.Id == id);
        }
    }
}

I-Form/I-Form/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using I_Form.Models;

namespace I_Form.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

         public IActionResult Next()
        {
            return View();
        }  
        public IActionResult LogedIn()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

I-Form/I-Form/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "I-Forms";
}

<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
<link href="~/css/site.css" rel="stylesheet" />


<body style="background: #2d3436">
</body>

<div class="welcome-section content-hidden">
    <div class="content-wrap">
        <ul class="fly-in-text">
            <li>W</li>
            <li>E</li>
            <li>L</li>
            <li>C</li>
            <li>O</li>
            <li>M</li>
            <li>E</li>
        </ul>
        <span class="enter-button nonClick">to <b>I-Forms</b></span>
        <a asp-controller="Home" asp-action="Next" class="enter-button">Click here to get started.</a>
    </div>
</div>


@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");
        <script type="text/javascript">

            $(function () {
                var welcomeSection = $('.welcome-section'),
                    enterButton = welcomeSection.find('content-hidden');

                setTimeout(function () {
                    welcomeSection.removeClass('content-hidden');
                }, 800);

                enterButton.on('click', function (e) {
                    e.preventDefault();
                    welcomeSection.addClass('content-hidden').fadeOut();
                })
            })

        </script>
    }
}

I-Form/I-Form/Views/Home/Next.cshtml
@using Microsoft.AspNetCore.Identity
@using I_Form.Data.Entities

@{
    ViewData["Title"] = "Next";
}

@inject SignInManager<I_Form.Data.User> SignInManager
@inject UserManager<I_Form.Data.User> UserManager



<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

<link href="~/css/HomeNext.css" rel="stylesheet" />
<link href="~/css/HoverEffect.css" rel="stylesheet" />

<header>
    <div class="menu-toggle" id="hamburger">
        <i class="fas fa-bars"></i>
    </div>
    <div class="overlay"></div>
    <div class="container">
        <nav>
            <h1 class="brand"><a asp-controller="Home" asp-action="Next">I<span>-</span>Forms</a></h1>
            <ul>
                <partial name="_LoginPartial" />

            </ul>
        </nav>
    </div>
    <div class="contentWrap">
        <div class="card">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <div class="content">
                <h2>Answer forms</h2>
                <p>Answer forms that are already created by users.</p>
                <a asp-controller="Forms" asp-action="Index">Read more</a>
            </div>
        </div>

        @if(User.Identity.IsAuthenticated)
        {

        <div class="card">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <div class="content">
                <h2>Create form</h2>
                <p>Create form and let other users answer it.</p>
                <a asp-controller="Forms" asp-action="Create">Read more</a>
            </div>
        </div>

        }
       

    </div>
</header>

@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");
        <script type="text/javascript">

            var open = document.getElementById('hamburger');
            var changeIcon = true;

            open.addEventListener("click", function () {

                var overlay = document.querySelector('.overlay');
                var nav = document.querySelector('nav');
                var icon = document.querySelector('.menu-toggle i');

                overlay.classList.toggle("menu-open");
                nav.classList.toggle("menu-open");

                if (changeIcon) {
                    icon.classList.remove("fa-bars");
                    icon.classList.add("fa-times");

                    changeIcon = false;
                }
                else {
                    icon.classList.remove("fa-times");
                    icon.classList.add("fa-bars");
                    changeIcon = true;
                }
            });

        </script>
    }
}